In [1]:
# A model that estimates the price range of Mobiles based on its features

In [29]:
# importing required libraries
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("mobile_price_range_data (2).csv") #reading the dataset/input file


In [30]:
#reading the first five rows/tuples from the dataset
df.head()     

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [4]:
df.tail() #reading the last five rows from the dataset

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[5 rows x 21 columns]

In [5]:
#it gives the no. of rows and columns of dataset
df.shape

(2000, 21)

In [28]:
# results a list of unique values
df.nunique() 

battery_power    1094
blue                2
clock_speed        26
dual_sim            2
fc                 20
four_g              2
int_memory         63
m_dep              10
mobile_wt         121
n_cores             8
pc                 21
px_height        1137
px_width         1109
ram              1562
sc_h               15
sc_w               19
talk_time          19
three_g             2
touch_screen        2
wifi                2
price_range         4
dtype: int64

In [31]:
#Prints information about the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [32]:
# prints the description of the data in hte dataframe
df.describe()

battery_power       blue  clock_speed     dual_sim           fc  \
count    2000.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     0.4950     1.522250     0.509500     4.309500   
std       439.418206     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       851.750000     0.0000     0.700000     0.000000     1.000000   
50%      1226.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.250000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  ...  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  ...   
mean      0.521500    32.046500     0.501750   140.249000     4.520500  ...   
std       0.499662    18.145715     0.288416    35.399655     2.287837  ...   
min       0.000000     2.000000     0.100000    80.000000     1.000000  ...   
25%       0.000000    16.000000     0.200000   109.000000     3.000000  ...   
50%       1.000000    32.000000     0.500000   141.000000     4.000000  ...   
75%       1.000000    48.000000     0.800000   170.000000     7.000000  ...   
max       1.000000    64.000000     1.000000   200.000000     8.000000  ...   

         px_height     px_width          ram         sc_h         sc_w  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    645.108000  1251.515500  2124.213000    12.306500     5.767000   
std     443.780811   432.199447  1084.732044     4.213245     4.356398   
min       0.000000   500.000000   256.000000     5.000000     0.000000   
25%     282.750000   874.750000  1207.500000     9.000000     2.000000   
50%     564.000000  1247.000000  2146.500000    12.000000     5.000000   
75%     947.250000  1633.000000  3064.500000    16.000000     9.000000   
max    1960.000000  1998.000000  3998.000000    19.000000    18.000000   

         talk_time      three_g  touch_screen         wifi  price_range  
count  2000.000000  2000.000000   2000.000000  2000.000000  2000.000000  
mean     11.011000     0.761500      0.503000     0.507000     1.500000  
std       5.463955     0.426273      0.500116     0.500076     1.118314  
min       2.000000     0.000000      0.000000     0.000000     0.000000  
25%       6.000000     1.000000      0.000000     0.000000     0.750000  
50%      11.000000     1.000000      1.000000     1.000000     1.500000  
75%      16.000000     1.000000      1.000000     1.000000     2.250000  
max      20.000000     1.000000      1.000000     1.000000     3.000000  

[8 rows x 21 columns]

In [7]:
#Checking whether null values are present or not
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [ ]:
# no null vales are present

In [8]:
x = df[['px_height']]
y = df['price_range']
print(type(x))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [9]:
#dividing the data into training and testing data

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)


(1500, 1)
(500, 1)
(1500,)
(500,)


In [10]:
# 1.Applying Logistic Regression

from sklearn.linear_model import LogisticRegression
m1 = LogisticRegression()
m1.fit(x_train,y_train)

LogisticRegression()

In [11]:
ypred1 = m1.predict(x_test) #Predicting 'y' values from x_test data
print(ypred1)

[0 3 1 0 3 0 0 1 0 3 3 0 0 3 3 3 0 0 0 3 0 3 0 3 0 0 0 1 1 1 1 3 0 0 3 0 3
 1 0 3 0 0 0 0 0 1 0 3 0 3 0 3 3 1 0 0 0 0 1 3 0 0 3 0 1 3 0 3 0 0 1 3 3 0
 0 0 0 1 3 3 0 3 3 3 0 0 0 0 0 0 0 0 0 0 1 3 0 3 1 0 3 3 1 0 0 3 1 3 3 1 0
 3 1 3 0 1 0 0 0 0 3 3 3 3 1 3 1 3 1 3 0 0 3 0 0 0 3 0 1 0 0 0 3 0 3 3 0 1
 0 3 3 0 3 3 1 0 0 0 0 0 0 0 3 0 3 1 0 0 0 1 0 3 1 3 0 0 0 0 3 0 0 3 0 0 3
 3 0 0 3 1 0 0 3 3 0 3 0 3 0 1 0 0 0 0 0 3 0 3 3 0 3 3 1 1 1 0 3 3 0 3 0 0
 1 0 1 3 3 3 0 3 0 3 1 3 1 0 3 0 0 0 3 3 3 0 0 3 3 0 1 0 0 0 0 3 0 3 3 1 0
 3 0 3 0 0 3 0 0 0 3 3 0 0 3 3 3 0 3 1 3 3 0 3 0 3 0 0 0 0 0 0 3 0 0 3 3 0
 3 3 3 3 3 3 0 0 0 3 0 1 3 0 3 3 0 0 0 0 3 0 0 0 0 3 0 3 3 3 1 0 0 0 0 0 0
 0 3 0 0 3 1 3 0 3 0 3 0 0 1 0 3 1 3 3 1 0 0 0 1 0 0 0 3 3 1 0 0 3 3 1 1 3
 3 0 0 0 0 0 1 0 3 1 3 0 0 0 0 1 3 0 0 3 3 0 0 0 3 0 1 0 0 0 0 0 3 0 3 3 0
 3 3 1 0 0 1 3 0 0 3 0 3 3 1 0 1 3 0 0 1 3 3 0 0 0 3 3 1 1 3 0 0 0 3 1 3 3
 1 3 3 0 1 3 0 3 0 0 3 0 0 0 3 0 0 1 3 0 3 0 0 3 1 1 0 0 1 3 0 3 0 0 0 3 3
 3 0 0 0 3 3 3 3 3 3 0 1 

In [12]:
res = print(pd.DataFrame({'y_test':y_test,'ypred1':ypred1}))


      y_test  ypred1
863        0       0
1353       3       3
1325       0       1
1297       3       0
1465       1       3
...      ...     ...
678        3       3
452        3       3
1422       2       0
176        0       0
841        1       0

[500 rows x 2 columns]


In [13]:
#y = mx+c
m = m1.coef_
c = m1.intercept_
print("slope",m)
print("intercept",c)

slope [[-5.64415712e-04]
 [ 1.35805125e-04]
 [-2.52059779e-05]
 [ 4.53816565e-04]]
intercept [ 0.33703759 -0.05850651  0.02319603 -0.30172712]


In [14]:
#Creating Logistic Function

def logistic(x,m,c):
  sig = 1/(1+np.exp(-(m*x+c)))
  print(sig)

In [15]:
logistic(129,m,c)


[[0.56567533 0.46721806 0.48759915 0.40744524]
 [0.58772207 0.48975452 0.51017732 0.42942237]
 [0.58268029 0.48456539 0.50498595 0.42434085]
 [0.59762523 0.50000896 0.52042322 0.43950166]]


In [16]:
#Computing Confusion matrix and Classification report

from sklearn.metrics import confusion_matrix,classification_report
cm_1 = confusion_matrix(y_test,ypred1)
print(cm_1)
print(classification_report(y_test,ypred1))

[[77 21  0 31]
 [58 16  0 44]
 [66 16  0 45]
 [47 18  0 61]]
              precision    recall  f1-score   support

           0       0.31      0.60      0.41       129
           1       0.23      0.14      0.17       118
           2       0.00      0.00      0.00       127
           3       0.34      0.48      0.40       126

    accuracy                           0.31       500
   macro avg       0.22      0.30      0.24       500
weighted avg       0.22      0.31      0.25       500



C:\Users\keert\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\keert\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\keert\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
# 2.Applying KNN Algorithm

df = pd.read_csv("mobile_price_range_data (2).csv")
from sklearn.neighbors import KNeighborsClassifier
m2 = KNeighborsClassifier(n_neighbors=15)
m2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [19]:
ypred2=m2.predict(x_test)
print(ypred2)

[2 3 2 0 0 2 0 0 2 0 0 2 0 3 0 3 0 0 1 3 0 3 0 1 2 3 2 0 1 0 2 2 0 2 3 0 3
 0 2 3 3 0 0 1 0 1 0 3 0 3 1 3 0 2 3 1 3 0 2 3 2 0 1 0 2 1 0 2 3 2 3 3 3 0
 0 0 2 1 3 3 0 3 0 3 2 3 0 2 0 1 0 0 0 3 0 0 0 0 0 0 1 3 2 0 1 3 1 3 3 1 0
 1 0 0 0 2 2 0 0 1 2 3 0 1 1 1 0 3 1 3 0 1 2 0 1 3 3 1 2 3 3 0 0 0 1 1 1 1
 1 0 2 0 0 2 3 2 0 0 1 2 0 3 3 1 3 0 2 0 1 2 0 3 3 3 1 2 1 0 1 3 1 1 2 0 0
 3 0 0 2 0 1 1 0 3 2 0 2 3 1 0 0 0 3 1 0 3 0 3 1 3 0 2 0 1 1 2 2 0 0 2 1 3
 0 3 1 2 1 1 2 0 0 1 1 3 0 0 3 0 1 2 3 1 3 2 2 3 3 2 3 0 2 0 3 3 1 0 1 1 0
 2 2 1 0 0 3 0 2 0 0 3 2 1 3 2 1 2 3 2 2 1 0 0 3 0 0 3 3 1 0 2 0 2 2 1 0 0
 2 3 3 3 3 3 0 1 3 0 0 0 1 0 3 3 2 1 0 2 1 2 1 0 0 1 3 1 3 3 0 1 0 0 0 1 0
 2 0 2 0 0 0 0 2 3 2 1 1 1 0 1 0 3 2 3 1 1 2 2 1 1 0 2 3 3 0 1 2 2 2 0 3 3
 3 3 2 0 3 1 2 2 2 0 3 0 1 2 0 0 2 0 3 2 1 3 0 1 3 3 0 2 0 2 2 2 0 0 0 3 0
 2 3 1 0 1 0 1 3 0 0 0 2 0 3 0 1 1 2 1 1 1 3 1 0 3 1 1 0 1 0 2 2 0 0 0 2 2
 1 0 3 2 1 3 0 0 0 0 3 0 2 3 3 2 0 0 0 3 1 2 2 3 2 0 0 0 1 2 0 2 2 0 1 3 3
 3 2 0 3 3 0 0 2 1 1 0 0 

In [21]:
#Computing Confusion matrix and Classification report

from sklearn.metrics import confusion_matrix,classification_report
cm_2 = confusion_matrix(y_test,ypred2)
print(cm_2)
classification_report(y_test,ypred2)

[[48 28 33 20]
 [41 23 24 30]
 [45 24 24 34]
 [43 29 23 31]]


'              precision    recall  f1-score   support\n\n           0       0.27      0.37      0.31       129\n           1       0.22      0.19      0.21       118\n           2       0.23      0.19      0.21       127\n           3       0.27      0.25      0.26       126\n\n    accuracy                           0.25       500\n   macro avg       0.25      0.25      0.25       500\nweighted avg       0.25      0.25      0.25       500\n'

In [22]:
# 3.Applying Decision Tree Classification

df = pd.read_csv("mobile_price_range_data (2).csv")
from sklearn.tree import DecisionTreeClassifier
m3 = DecisionTreeClassifier(criterion='gini',max_depth=4,min_samples_split = 12)
m3.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=4, min_samples_split=12)

In [23]:
ypred3 = m3.predict(x_test)
print(ypred3)

[0 2 1 0 1 0 0 1 2 1 1 0 0 3 1 1 0 0 0 1 0 3 0 1 1 0 0 1 1 1 1 1 0 0 1 0 3
 1 0 3 0 0 0 0 2 1 0 1 0 1 0 2 1 1 0 0 0 0 1 1 0 2 1 0 1 3 2 1 0 0 1 1 1 2
 0 0 0 1 1 3 0 3 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 2 3 1 0 0 1 1 3 1 1 0
 1 1 1 0 1 0 0 0 0 3 3 1 1 1 1 1 3 1 3 1 0 1 0 0 0 2 0 1 0 0 0 1 0 1 2 0 1
 0 1 2 0 1 1 1 0 0 2 0 0 0 0 1 0 3 1 1 0 0 1 0 1 1 3 1 0 1 0 1 0 1 1 0 0 1
 3 0 0 1 1 1 0 1 3 0 1 2 3 0 1 0 0 0 0 0 2 2 1 1 0 1 3 1 1 1 0 3 1 0 1 0 0
 1 0 1 1 1 1 1 1 0 1 1 3 1 2 3 0 0 0 1 1 1 0 0 1 3 0 1 2 2 0 0 1 0 1 1 1 0
 1 0 1 0 2 3 2 2 0 1 1 2 0 1 2 1 0 3 1 1 1 0 1 0 1 0 0 0 0 0 2 1 0 0 1 1 0
 3 3 1 1 3 1 2 0 0 1 0 1 1 2 1 1 0 1 2 0 1 2 0 0 0 2 0 1 3 3 1 2 0 0 0 1 0
 0 1 0 2 1 1 1 0 3 1 1 0 0 1 0 1 1 1 3 1 0 0 1 1 0 0 1 1 3 1 0 0 3 3 1 1 2
 1 0 0 0 0 2 1 0 3 1 3 2 0 2 0 1 1 0 0 3 2 0 0 0 1 0 1 0 0 0 0 2 1 0 1 3 0
 1 1 1 0 0 1 1 0 0 1 1 1 1 1 0 1 1 1 0 1 1 3 1 0 0 1 1 1 1 1 0 0 0 1 1 1 3
 1 1 3 0 1 1 0 1 0 0 1 0 0 0 3 1 0 1 1 0 1 1 0 3 1 1 0 2 1 3 2 3 2 0 0 3 3
 1 1 0 0 1 1 1 1 1 2 0 1 

In [24]:
#Computing Confusion matrix and Classification report

from sklearn.metrics import confusion_matrix , classification_report
cm_3 = confusion_matrix(y_test,ypred3)
print(cm_3)
classification_report(y_test,ypred3)

[[57 50 15  7]
 [47 47 10 14]
 [55 53  8 11]
 [40 61  9 16]]


'              precision    recall  f1-score   support\n\n           0       0.29      0.44      0.35       129\n           1       0.22      0.40      0.29       118\n           2       0.19      0.06      0.09       127\n           3       0.33      0.13      0.18       126\n\n    accuracy                           0.26       500\n   macro avg       0.26      0.26      0.23       500\nweighted avg       0.26      0.26      0.23       500\n'

In [25]:
# 4.Applying Random Forest Clssification

df = pd.read_csv("mobile_price_range_data (2).csv")
from sklearn.ensemble import RandomForestClassifier
m4 = RandomForestClassifier(n_estimators= 80,criterion='entropy',max_depth=6,min_samples_split = 12)
m4.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=6, min_samples_split=12,
                       n_estimators=80)

In [26]:
ypred4= m4.predict(x_test)
print(ypred4)

[2 2 1 0 1 2 0 1 1 1 2 0 2 3 1 3 2 2 2 2 0 3 2 1 2 2 1 1 1 2 2 2 1 2 3 2 3
 2 0 3 0 2 0 0 0 1 2 1 0 1 0 3 0 1 0 0 0 2 1 2 2 0 1 0 1 1 2 2 0 0 1 1 3 0
 2 0 0 1 1 3 0 3 1 1 3 0 0 2 0 0 0 0 0 0 1 1 0 1 2 2 1 3 1 0 1 1 1 3 1 1 0
 1 0 3 0 2 0 0 0 1 2 3 1 1 1 1 0 3 1 3 2 0 1 0 0 2 3 2 1 3 0 0 1 0 1 2 0 1
 1 1 2 1 3 2 3 2 0 0 1 2 3 2 3 1 3 1 2 0 2 1 0 2 1 3 1 2 2 2 1 0 1 1 2 0 1
 3 0 0 3 2 2 2 1 3 2 2 0 3 1 2 2 2 0 1 0 3 0 1 1 0 1 2 1 3 1 2 2 1 0 2 1 0
 2 0 1 2 1 1 2 2 0 1 1 3 1 0 3 0 0 2 1 1 1 0 2 1 3 2 2 0 0 0 0 2 1 3 1 1 0
 3 0 1 0 2 3 0 0 1 3 1 0 1 2 2 1 1 3 1 2 1 0 1 0 0 0 2 0 0 0 2 1 0 2 1 0 0
 2 3 3 2 3 2 0 0 3 3 2 1 1 0 1 1 2 2 0 1 1 2 2 0 0 1 0 1 3 3 1 1 0 0 0 2 0
 2 0 3 0 1 2 3 2 3 2 1 2 2 0 1 0 1 2 3 1 1 2 2 1 2 0 2 1 2 0 1 2 3 2 0 1 2
 3 0 2 0 2 0 2 2 2 0 3 0 0 2 0 0 2 2 2 2 2 2 2 0 2 3 0 2 0 2 2 0 3 0 1 3 0
 1 1 1 0 0 2 1 2 0 1 1 1 1 0 0 1 1 2 0 1 1 1 1 0 2 1 1 1 1 1 2 1 0 1 1 2 3
 1 3 3 2 1 1 0 1 0 0 1 0 2 0 3 2 0 0 0 0 1 2 2 3 2 2 0 0 1 3 0 2 0 0 1 3 3
 1 2 0 0 1 1 1 2 1 2 0 1 

In [27]:
#Computing Confusion matrix and Classification report

from sklearn.metrics import confusion_matrix , classification_report
cm_4 = confusion_matrix(y_test,ypred4)
print(cm_4)
classification_report(y_test,ypred4)

[[45 36 38 10]
 [35 37 33 13]
 [42 36 31 18]
 [25 45 33 23]]


'              precision    recall  f1-score   support\n\n           0       0.31      0.35      0.33       129\n           1       0.24      0.31      0.27       118\n           2       0.23      0.24      0.24       127\n           3       0.36      0.18      0.24       126\n\n    accuracy                           0.27       500\n   macro avg       0.28      0.27      0.27       500\nweighted avg       0.28      0.27      0.27       500\n'

In [ ]:
# By observing the accuracy of every applied algorithm, Logistic Regression has given the highest accuracy 
#for the taken dataset